#!/bin/bash

chmod +x *
chmod -R 777 ../data
chmod -R 777 ../data/*
chmod -R 777 ../code
chmod -R 777 ../code/*

# ================ Configuration parameters ====================
ID=6sper    # specify the input map folder path (the job name)
TIME=90     # specify the number of seconds to be used per iteration for compute heavy step
CNT=0.028   # specify the recommended contour level for your map
use_AF=1    # specify 1 if you uploaded Alpha Fold model. Otherwise specify 0
MODELS=1    # specify number of models to be generated by Rosetta
# ===============================================================

echo "DeepMainMast Starting"

lscpu
nvidia-smi

# Download some big files from kiharalab website
wget -O /results/partial_thread.static.linuxgccrelease https://kiharalab.org/emsuites/deepmainmast/dmmbin/partial_thread.static.linuxgccrelease
wget -O /results/rosetta_scripts.static.linuxgccrelease https://kiharalab.org/emsuites/deepmainmast/dmmbin/rosetta_scripts.static.linuxgccrelease

if [[ "$use_AF" -eq 1 ]]; then
    ./run_pipeline_with_af.sh $ID $TIME $CNT $MODELS
else
    ./run_pipeline_without_af.sh $ID $TIME $CNT $MODELS
fi
